### ISSUE TITLE
[Feature request] AutoHotkey output panel hide

### ISSUE THREAD

**Issue by Kristinita** [albertosantini/sublimetext-buildnext#10]
### Request

It would be nice, if you add opportunity hide AutoHotkey panel, if script run was successfully.

### Justification

I need hide panel manually, I spend time on it.

### Steps for reproduce

I install AutoHotkey → I install and configure [SublimeAutoHotkey](https://github.com/ahkscript/SublimeAutoHotkey) → I create any `ahk` file, for example:

```autohotkey
:R*:/Sasha::Sasha is amazing!
```

<kbd>Ctrl+Shift+P</kbd> → `AutoHotkey - Run` → if script successful run, output panel not hide for me.

![Actual behavior](http://i.imgur.com/5UnrSsM.gif)

Thanks.

**Comment by albertosantini** [comment]
Thanks for the suggestion.

The plugin works with the native `Build` system.
It is not integrated with other systems, like AutoHotkey, unless you create a build system with it, as you know with respect to the other issue you opened.

Another path is contributing to SublimeAutoHotkey.

As in another issue of yours I suggested the following snippet to close the output panel.

```
...
        exit_code = proc.exit_code()
        errors_len = len(self.output_view.find_all_results())

        if (exit_code != None and exit_code != 0) or errors_len > 0:
            self.window.run_command("show_panel", {"panel": "output.exec"})
        else:
            self.window.run_command("hide_panel", {"panel": "output.exec"})
...
```

You may use that code in a plugin of yours to integrate AutoHotkey or to enhance another plugin.

So this is issue it is  `won't fix`.
