### ISSUE TITLE
[Bug] Browser builds and AutoHotkey scripts not work after upgrade

### ISSUE THREAD

**Issue by Kristinita** [albertosantini/sublimetext-buildnext#9]
### Summary

Browser builds and SublimeAutoHotkey scripts not worked correctly if Build Next is enabled in Build 3124. 

In Build 3114 all works good. When I disable Build Next all works good.

### Expected behavior

+ Successful open my HTML-pages in browser
+ Run and compiled my AutoHotkey scripts

### Actual behavior

My browsers not open and AutoHotkey scripts not run or compiled.

#### Firefox

My Firefox `.sublime-build` file:

	{
		"shell_cmd": "\"E:/Firefox/FirefoxPortable.exe\" \"$file\"",
		"selector": "text.html.basic, text.xml"
	}

I select this Build system → I press <kbd>Ctrl+B</kbd> in any HTML file. My files not open in browser.

#### AutoHotkey

See [thread](https://forum.sublimetext.com/t/not-run-or-compile-autohotkey-scripts-after-upgrade/23035/1) in Sublime Text forum.

### Additional information

See also traceback in #8 issue.

### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3124

Thanks.

**Comment by albertosantini** [comment]
Update to Build Next 1.4.0.
